apiVersion: apps/v1
kind: Deployment
metadata:
  name: github-api-service # Deployment name
spec:
  replicas: 1 # Runs one instance
  selector:
    matchLabels:
      app: github-api-service # Match pods to deployment
  template:
    metadata:
      labels:
        app: github-api-service
    spec:
      containers:
      - name: github-api-service
        image: richie223/github-api-service:latest
        env:
        - name: TOKEN
          valueFrom:
            secretKeyRef:
              name: github-secrets
              key: TOKEN
        - name: OWNER
          valueFrom:
            secretKeyRef:
              name: github-secrets
              key: OWNER
        ports:
        - containerPort: 8080
