name: Assignment Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.23.4

      - name: Install dependencies
        run: go mod tidy

      - name: Run Tests
        run: go test ./... -v 

  lint:
    name: Lint Code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.23.4

      - name: Install golangci-lint
        run: sudo snap install golangci-lint --classic

      - name: Run Linter
        run: golangci-lint run ./...

  security:
    name: Run Security Scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.23.4

      - name: Install Gosec
        run: go install github.com/securego/gosec/v2/cmd/gosec@latest

      - name: Run Security Scan
        run: gosec ./...
  
  build:
    name: Buil Docker image
    runs-on: ubuntu-latest
    needs: [test, lint, security]
    steps:
      - uses: actions/checkout@v4
      - uses: docker/login-action@v2
        with:
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
      - run: docker build -t ${{ secrets.USERNAME }}/github-api-service:latest .
      - run: docker push ${{ secrets.USERNAME }}/github-api-service:latest
      - run: docker logout

  deploy:
    name: Deploy to Minikube
    runs-on: ubuntu-latest
    needs: [build]

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Minikube
        run: |
          curl -LO https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
          sudo install minikube-linux-amd64 /usr/local/bin/minikube
          curl -LO "https://dl.k8s.io/release/v1.23.0/bin/linux/amd64/kubectl"
          sudo install kubectl /usr/local/bin/
          
          minikube start --driver=docker

      - name: Create secret
        run: |
          kubectl create secret generic github-secret \
          --from-literal=token=${{ secrets.TOKEN }} \
          --from-literal=owner=${{ secrets.USER }}

      - name: Apply Kubernetes Deployment
        run: |
          kubectl apply -f kubernetes/deployment.yml 
          kubectl apply -f kubernetes/service.yml 
        
          # Get deployment status and service info
          echo "Deployment Status:"
          kubectl get deployments
          echo "Service Status:"
          kubectl get services
          echo "Pods Status:"
          kubectl get pods
          # Get service URL
          echo "Service URL:"
          minikube service github-api-service --url